
# PLEASE DO NOT EDIT THIS FILE DIRECTLY.
# This is generated by Fog's release tasks in /home/hedge/.rvm/gems/ruby-1.9.2-p0@fog/gems/rake-0.8.7/lib/rake.rb:2470:in `rakefile_location'.
# That is, Fog's version numbers change on release.
# To make a non-sequential number change, please run the rake command
#    rake release:custom[3,7,1,2]
module ::Fog
  module Version
    MAJOR = 0
    MINOR = 3
    PATCH = 23
    BUILD = 0
    STRING = "#{MAJOR}.#{MINOR}.#{PATCH}.#{BUILD}"
  end
end
