require 'fog/openstack/compute'
require 'fog/openstack/identity'
require 'fog/openstack/image'
require 'fog/openstack/metering'
require 'fog/openstack/network'
require 'fog/openstack/orchestration'
require 'fog/openstack/storage'
require 'fog/openstack/volume'
